### PR TITLE
Update application.yml in Getting Started guide

### PR DESCRIPTION
**Pull request by rozagerardo**
Update `application.yml` in Getting Started guide so it aligns with the `UserDetailsService` `@Bean` defined in the _"Defining Required Components"_ section.

Issue gh-1186

### CODE REVIEW

**Comment by jgrandja** [comment]
Thanks for the PR @rozagerardo.

Just a heads up that I updated the PR description and associated commit message as the original description stated that this fixed gh-1475, which is not the case. We'll need to wait until Boot `3.2.2` is released to validate the fix.

**Comment by rozagerardo** [comment]
Cool @jgrandja. A quick question, though, if this doesn't "fix" https://github.com/spring-projects/spring-authorization-server/issues/1475, then how will we resolve that issue?

Anyway, Boot `3.2.2` is GA now. The minimal configuration seems to be working with this version.

Here is a small sample to check it out (I included an OAuth2 Client and a RS to check the whole flow, just in case):

https://github.com/rozagerardo/samples/tree/spring/auth-server-minimal-config

Also, as I was working on the setup, I realized we're using the `{noop}` prefix for the `client-secret`, and I was wondering if we should follow the same approach for the user `password` we're including at this stage, mainly for consistency (it works either way). Let me know if I should modify/re-create the PR with that small change :)

**Comment by jgrandja** [comment]
@rozagerardo 

> A quick question, though, if this doesn't "fix" https://github.com/spring-projects/spring-authorization-server/issues/1475, then how will we resolve that issue?

See this [comment](https://github.com/spring-projects/spring-authorization-server/issues/1475#issuecomment-1916822828)

**Comment by jgrandja** [comment]
@rozagerardo 

> I was wondering if we should follow the same approach for the user `password` we're including at this stage, mainly for consistency (it works either way)

I think we are fine to leave as-is. FYI, `UserDetailsServiceAutoConfiguration` automatically prefixes the password with `{noop}`

**Pull request closed without merging**
